[package]
name = "dashchat-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
iroh = { workspace = true }
iroh-blobs = { workspace = true }
futures = "0.3"
log = "0.4"
tokio = { version = "1", features = ["time", "sync", "rt", "macros"] }
tracing = { workspace = true }

serde = { workspace = true, optional = true }
ciborium = { workspace = true, optional = true }

[dev-dependencies]
serde_json = { workspace = true }
tokio = { version = "1", features = ["time", "sync", "macros", "rt-multi-thread", "test-util"] }

[features]
default = []
cbor = ["serde", "ciborium"]
