[profile.release]
opt-level = 3
panic = "abort"
lto = "fat"
codegen-units = 1
# inherits = "release"

[workspace]
members = ["crates/*", "src-tauri"]
resolver = "2"

[workspace.dependencies]

ciborium = "0.2.2"
derive_more = { version = "2.1.1", features = ["full"] }
named-id = { git = "https://github.com/maackle/named-id.git" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

dashchat-compat = { path = "crates/dashchat-compat" }
mailbox-client = { path = "crates/mailbox-client", features = ["named-id"] }
mailbox-server = { path = "crates/mailbox-server" }

p2panda-auth = { git = "https://github.com/maackle/p2panda.git", branch = "dashchat-auth-sqlite", features = [
  "processor",
] }
p2panda-core = { git = "https://github.com/maackle/p2panda.git", branch = "dashchat-auth-sqlite" }
p2panda-encryption = { git = "https://github.com/maackle/p2panda.git", branch = "dashchat-auth-sqlite" }
p2panda-discovery = { git = "https://github.com/maackle/p2panda.git", branch = "dashchat-auth-sqlite" }
p2panda-net = { git = "https://github.com/maackle/p2panda.git", branch = "dashchat-auth-sqlite" }
p2panda-store = { git = "https://github.com/maackle/p2panda.git", branch = "dashchat-auth-sqlite", features = [
  "sqlite",
] }
p2panda-stream = { git = "https://github.com/maackle/p2panda.git", branch = "dashchat-auth-sqlite" }
p2panda-sync = { git = "https://github.com/maackle/p2panda.git", branch = "dashchat-auth-sqlite" }
p2panda-spaces = { git = "https://github.com/maackle/p2panda.git", branch = "dashchat-auth-sqlite", features = [
  "test_utils",
] }


# [patch."https://github.com/maackle/p2panda.git"]
# p2panda-auth = { path = "/home/michael/gitfork/p2panda/p2panda-auth" }
# p2panda-core = { path = "/home/michael/gitfork/p2panda/p2panda-core" }
# p2panda-encryption = { path = "/home/michael/gitfork/p2panda/p2panda-encryption" }
# p2panda-discovery = { path = "/home/michael/gitfork/p2panda/p2panda-discovery" }
# p2panda-net = { path = "/home/michael/gitfork/p2panda/p2panda-net" }
# p2panda-store = { path = "/home/michael/gitfork/p2panda/p2panda-store" }
# p2panda-stream = { path = "/home/michael/gitfork/p2panda/p2panda-stream" }
# p2panda-sync = { path = "/home/michael/gitfork/p2panda/p2panda-sync" }
# p2panda-spaces = { path = "/home/michael/gitfork/p2panda/p2panda-spaces" }
