[package]
name = "local-hub-discovery"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
log = "0.4"
futures = "0.3"
mdns-sd = "0.20"
tokio = { version = "1", features = ["macros", "net", "rt", "sync", "time"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
