[package]
name = "mailbox-api"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
base64 = "0.22.0"
blake3 = { version = "1.8.3", features = ["serde"] }
bytes = { version = "1.11.0", features = ["serde"] }
derive_more = { version = "1.0.0", features = ["full"] }
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
named-id = { git = "https://github.com/maackle/named-id.git" }

proptest = { version = "1.10.0", optional = true }
proptest-derive = { version = "0.8.0", optional = true }
redb = { version = "3.1", optional = true }

[features]
default = ["redb", "proptest", "proptest-derive"]
