[package]
name = "dashchat-node"
version = "0.1.0"
description = "dashchat's p2p backend"
authors = ["you"]
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
serde_json = "1"

mailbox-client = { workspace = true }
mailbox-server = { workspace = true }

p2panda = { workspace = true, features = ["test_utils"] }
p2panda-auth = { workspace = true }
p2panda-core = { workspace = true }
p2panda-net = { workspace = true }
p2panda-store = { workspace = true }
p2panda-spaces = { workspace = true }

iroh = { workspace = true }
iroh-blobs = { workspace = true }

aliased = { workspace = true }
anyhow = "1.0.95"
dashchat-compat = { workspace = true }
dashchat-utils = { workspace = true }
ed25519-dalek = { workspace = true }
thiserror = "2.0"
async-trait = "0.1.85"
derive_more = { version = "1.0.0", features = ["full"] }
futures = "0.3"
tokio = { version = "1.43.0", features = ["fs"] }
base64 = "0.22"
blake3 = "1.8.2"
chrono = { version = "0.4.42", features = ["serde"] }
hex = "0.4.3"
rand = "0.9.2"
tokio-stream = "0.1.17"
tokio-util = "0.7"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
bytes = { workspace = true }
sqlx = "0.8.6"

tempfile = { version = "3.24", optional = true }
nanoid = { version = "0.4", optional = true }
regex = { version = "1", optional = true }

[target.'cfg(target_os = "android")'.dependencies]
if-watch = { version = "3", features = ["tokio"] }

[dev-dependencies]
dashchat-node = { path = ".", features = ["testing"] }
mailbox-server = { path = "../mailbox-server", features = ["test_utils"] }
mailbox-local-server = { workspace = true }
itertools = "0.14.0"
maplit = "1.0"
pretty_assertions = "1.4.1"
tempfile = "3"
p2panda-store = { workspace = true, features = ["test_utils"] }

[features]
default = ["testing", "instrument"]
instrument = []
testing = ["tempfile", "nanoid", "regex", "p2panda-store/test_utils"]
p2p = []
