[package]
name = "mailbox-local-server"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
dashchat-utils = { workspace = true }
mailbox-server = { workspace = true }
mailbox-mdns-discovery = { workspace = true }
anyhow = "1"
log = "0.4"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["rt"] }
mdns-sd = "0.17"
tracing = "0.1"
