[package]
name = "mailbox-local-server"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "mailbox-local-server"
path = "src/main.rs"

[dependencies]
dashchat-utils = { workspace = true }
mailbox-server = { workspace = true }
iroh = { workspace = true }
iroh-blobs = { workspace = true }
anyhow = "1"
log = "0.4"
tokio = { version = "1", features = ["full"] }
mdns-sd = "0.20"
clap = { version = "4.5", features = ["derive"] }
futures = "0.3"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
