name: "cargo nextest"
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  cargo-nextest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt install libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: '' # TODO: remove this when we want to disallow warnings in our rust code in CI

      - name: Cache Rust target
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - name: Test
        run: cargo nextest run
