name: Build and deploy site
on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-25.11

      - uses: cachix/cachix-action@v15
        with:
          name: darksoil-studio

      - name: Install and Build 🔧
        run: |
          nix develop --accept-flake-config --command bash -c "pnpm install && pnpm -F site build"

      - name: Upload artifact 📦
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/site/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy 🚀
        id: deployment
        uses: actions/deploy-pages@v4
